#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "TechFeed"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Gethugothemes"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# main sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright text
copyright = "Designed & Developed by [GetHugoThemes](https://gethugothemes.com)"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# author
[author_block]
title= "WELCOME TO MY BLOG"
image= "images/author.jpg"
content= "My name is Linda Smith. I am a writer, I like to travel and I love to photograph beautiful nature places and happy peoples."

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
icon = "fab fa-facebook-f"
link = "#"

[[social]]
icon = "fab fa-twitter"
link = "#"

[[social]]
icon = "fab fa-instagram"
link = "#"

[[social]]
icon = "fab fa-dribbble"
link = "#"